site_name: Family-Management-Contribution-System-Documentation
site_url: https://Vinnie-8.github.io/family-management-contribution-system/
copyright: Copyright &copy; 2026 Vincent Muoki

nav:
  - Home: index.md
  - User Research:
      - Overview: user_research/index.md
      - Summary: user_research/summary.md
      - Feedback: user_research/feedback.md
  - Authentication & Authorization:
      - Case Study: Authentication_Authorization_study/auth_casestudy.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false