"""initial migration

Revision ID: 4ef254077e8d
Revises: 
Create Date: 2026-10-01 11:10:40.214945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ef254077e8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_family_id'), 'events', ['family_id'], unique=False)
    op.create_table('financial_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_years_family_id'), 'financial_years', ['family_id'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_family_id'), 'households', ['family_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('agenda', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_family_id'), 'meetings', ['family_id'], unique=False)
    op.create_table('standing_funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standing_funds_family_id'), 'standing_funds', ['family_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('includes_minors', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_family_id'), 'campaigns', ['family_id'], unique=False)
    op.create_index(op.f('ix_campaigns_financial_year_id'), 'campaigns', ['financial_year_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_number', sa.String(length=8), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id_number IS NULL OR id_number ~ '^[0-9]{8}$'", name='check_id_number_format'),
    sa.CheckConstraint("phone_number IS NULL OR phone_number ~ '^[0-9]{10}$'", name='check_phone_format'),
    sa.CheckConstraint('is_minor = True OR phone_number IS NOT NULL OR email IS NOT NULL', name='check_adult_has_contact'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_members_family_id'), 'members', ['family_id'], unique=False)
    op.create_index(op.f('ix_members_household_id'), 'members', ['household_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'member_id', name='uq_meeting_member')
    )
    op.create_index(op.f('ix_attendances_meeting_id'), 'attendances', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_attendances_member_id'), 'attendances', ['member_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('actor_member_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'delete', 'deactivate_member', 'reset_password')", name='chk_audit_action'),
    sa.CheckConstraint("entity_type IN ('member', 'household', 'contribution_rule')", name='chk_audit_entity_type'),
    sa.ForeignKeyConstraint(['actor_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_member_id'), 'audit_logs', ['actor_member_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_family_id'), 'audit_logs', ['family_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_event_id'), 'budgets', ['event_id'], unique=False)
    op.create_table('campaign_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'event_id', name='uq_campaign_event')
    )
    op.create_index(op.f('ix_campaign_events_campaign_id'), 'campaign_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_events_event_id'), 'campaign_events', ['event_id'], unique=False)
    op.create_table('contribution_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('member_category', sa.String(), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('in_kind_item', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_rules_campaign_id'), 'contribution_rules', ['campaign_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_documents_entity_type'), 'documents', ['entity_type'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('standing_fund_id', sa.UUID(), nullable=True),
    sa.Column('beneficiary_member_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['standing_fund_id'], ['standing_funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_event_id'), 'expenses', ['event_id'], unique=False)
    op.create_index(op.f('ix_expenses_family_id'), 'expenses', ['family_id'], unique=False)
    op.create_index(op.f('ix_expenses_financial_year_id'), 'expenses', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_expenses_standing_fund_id'), 'expenses', ['standing_fund_id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_member_id'), 'fines', ['member_id'], unique=False)
    op.create_table('guardian_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guardian_member_id', sa.UUID(), nullable=False),
    sa.Column('minor_member_id', sa.UUID(), nullable=False),
    sa.Column('relationship_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['minor_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_member_id', 'minor_member_id', name='uq_guardian_minor')
    )
    op.create_index(op.f('ix_guardian_links_guardian_member_id'), 'guardian_links', ['guardian_member_id'], unique=False)
    op.create_index(op.f('ix_guardian_links_minor_member_id'), 'guardian_links', ['minor_member_id'], unique=False)
    op.create_table('handover_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('outgoing_member_id', sa.UUID(), nullable=True),
    sa.Column('incoming_member_id', sa.UUID(), nullable=False),
    sa.Column('term_start', sa.Date(), nullable=False),
    sa.Column('term_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incoming_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['outgoing_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'role_id', name='uq_member_role')
    )
    op.create_index(op.f('ix_member_roles_member_id'), 'member_roles', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_roles_role_id'), 'member_roles', ['role_id'], unique=False)
    op.create_table('minutes_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minutes_records_meeting_id'), 'minutes_records', ['meeting_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_member_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_member_id'), 'notifications', ['recipient_member_id'], unique=False)
    op.create_table('pledges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fulfilled_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pledges_campaign_id'), 'pledges', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_pledges_member_id'), 'pledges', ['member_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pledge_id', sa.UUID(), nullable=True),
    sa.Column('standing_fund_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('mpesa_transaction_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['pledge_id'], ['pledges.id'], ),
    sa.ForeignKeyConstraint(['standing_fund_id'], ['standing_funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('mpesa_transaction_code')
    )
    op.create_index(op.f('ix_payments_member_id'), 'payments', ['member_id'], unique=False)
    op.create_index(op.f('ix_payments_pledge_id'), 'payments', ['pledge_id'], unique=False)
    op.create_index(op.f('ix_payments_standing_fund_id'), 'payments', ['standing_fund_id'], unique=False)
    op.create_table('pledge_installments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pledge_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pledge_id'], ['pledges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pledge_installments_pledge_id'), 'pledge_installments', ['pledge_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['raised_by_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_payment_id'), 'disputes', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_payment_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_pledge_installments_pledge_id'), table_name='pledge_installments')
    op.drop_table('pledge_installments')
    op.drop_index(op.f('ix_payments_standing_fund_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_pledge_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_member_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_pledges_member_id'), table_name='pledges')
    op.drop_index(op.f('ix_pledges_campaign_id'), table_name='pledges')
    op.drop_table('pledges')
    op.drop_index(op.f('ix_notifications_recipient_member_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_minutes_records_meeting_id'), table_name='minutes_records')
    op.drop_table('minutes_records')
    op.drop_index(op.f('ix_member_roles_role_id'), table_name='member_roles')
    op.drop_index(op.f('ix_member_roles_member_id'), table_name='member_roles')
    op.drop_table('member_roles')
    op.drop_table('handover_records')
    op.drop_index(op.f('ix_guardian_links_minor_member_id'), table_name='guardian_links')
    op.drop_index(op.f('ix_guardian_links_guardian_member_id'), table_name='guardian_links')
    op.drop_table('guardian_links')
    op.drop_index(op.f('ix_fines_member_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_expenses_standing_fund_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_financial_year_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_family_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_event_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_documents_entity_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_contribution_rules_campaign_id'), table_name='contribution_rules')
    op.drop_table('contribution_rules')
    op.drop_index(op.f('ix_campaign_events_event_id'), table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_campaign_id'), table_name='campaign_events')
    op.drop_table('campaign_events')
    op.drop_index(op.f('ix_budgets_event_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_audit_logs_family_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_member_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendances_member_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_meeting_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_members_household_id'), table_name='members')
    op.drop_index(op.f('ix_members_family_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_campaigns_financial_year_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_family_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_standing_funds_family_id'), table_name='standing_funds')
    op.drop_table('standing_funds')
    op.drop_index(op.f('ix_meetings_family_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_households_family_id'), table_name='households')
    op.drop_table('households')
    op.drop_index(op.f('ix_financial_years_family_id'), table_name='financial_years')
    op.drop_table('financial_years')
    op.drop_index(op.f('ix_events_family_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('roles')
    op.drop_table('families')
    # ### end Alembic commands ###
